export const btnsConfig1 = [
    {id: 1, value: "%"},
    {id: 2, value:  "sqrt"},
    {id: 3, value: "1"},
    {id: 4, value: "1"},
    {id: 5, value: "CE"},
    {id: 6, value: "C"},
    {id: 7, value: "<-"},
    {id: 8, value: "/"},
    {id: 9, value: "7"},
    {id: 10, value: "8"},
    {id: 11, value: "9"},
    {id: 12, value: "*"},
    {id: 13, value: "4"},
    {id: 14, value: "5"},
    {id: 15, value: "6"},
    {id: 16, value: "-"},
    {id: 17, value: "1"},
    {id: 18, value: "2"},
    {id: 19, value: "3"},
    {id: 20, value: "+"},
    {id: 21, value: "!"},
    {id: 22, value: "0"},
    {id: 23, value: "."},
    {id: 24, value: "="},
]